version: "2"

services:
  postgres-slave:
    image: "nebirhos/postgres-replication"
    ports:
      - 5433:5432
    links:
      - postgres-master
    env_file:
      - ./postgres.env
      - ./postgres-slave.env
    volumes:
      - 'pg-slave:/var/lib/postgresql/data'

  postgres-master:
    image: "nebirhos/postgres-replication"
    ports:
      - 5432:5432
    env_file:
      - ./postgres.env
    volumes:
      - 'pg:/var/lib/postgresql/data'
            
  ethereum:
    image: ethereum/client-go:v1.7.2
    env_file:
      - ./geth.env
    restart: always
    expose:
      - "8545"
    command: --rpc --rpcaddr 0.0.0.0 --syncmode "light"

  chainlink:
    build: "chainlink/"
    env_file:
      - ./chainlink.env
    restart: always
    ports: 
      - "5100:5100"
    links:
      - "ethereum"
      - "postgres-master"
      - "postgres-slave"
    volumes:
      - .:/host

volumes:
  pg: ./master
  pg-slave: ./slave